name: Update to latest zig nightly

on:
  # push:
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 11,23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          bb: 'latest'

      - name: Get babashka version
        run: bb zig-updater.clj

      - name: Commit and push if it changed
        run: |-
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
