name: Update to latest zig nightly

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 11,23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python zig-updater.py

      - name: Commit and push if it changed
        run: |-
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
